language: python

python:
- 3.7

dist: xenial

sudo: true

services:
- mysql

addons:
  apt_packages:
  - libcups2-dev

install:
- pip install flake8 coveralls tox
- pip install -e .
- pip install -r requirements.txt

before_script:
- flake8 edc_device
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=edc_device setup.py test

after_success:
- coveralls
  